const FeelingsList = [
  { name: 'happy', unicode: '&#128515;', emoji: '😃' },
  { name: 'excited', unicode: '&#128516;', emoji: '😄' },
  { name: 'loved', unicode: '&#128536;', emoji: '😘' },
  { name: 'sad', unicode: '&#128542;', emoji: '😞' },
  { name: 'lovely', unicode: '&#128536;', emoji: '😘' },
  { name: 'thankful', unicode: '&#128522;', emoji: '😊' },
  { name: 'blessed', unicode: '&#128519;', emoji: '😇' },
  { name: 'in love', unicode: '&#128536;', emoji: '😘' },
  { name: 'crazy', unicode: '&#128518;', emoji: '😆' }
  // { name: 'happy', emoji: '😀' },
  // { name: 'blessed', emoji: '😇' },
  // { name: 'loved', emoji: '😘' },
  // { name: 'sad', emoji: '😟' },
  // { name: 'lovely', emoji: '😘' },
  // { name: 'thankful', emoji: '😃' },
  // { name: 'excited', emoji: '😁' },
  // { name: 'in love', emoji: '😘' },
  // { name: 'crazy', emoji: '🤣' }
  // {name:'grateful', emoji:''},
  // {name:'blissful', emoji:''},
  // {name:'fantastic', emoji:''},
  // {name:'silly', emoji:''},
  // {name:'cool', emoji:''},
  // {name:'wonderful', emoji:''},
  // {name:'amused', emoji:''},
  // {name:'relaxed', emoji:''},
  // {name:'positive', emoji:''},
  // {name:'chill', emoji:''},
  // {name:'joyful', emoji:''},
  // {name:'tired', emoji:''},
  // {name:'motivated', emoji:''},
  // {name:'proud', emoji:''},
  // {name:'delighted', emoji:''},
  // {name:'emotional', emoji:''},
  // {name:'sick', emoji:''},
];

export default FeelingsList;
